plugins:
  - jekyll-optional-front-matter

# 设置基础URL - GitHub Pages部署时为仓库名，自定义域名时为空
baseurl: "/LTS_site"
url: "https://longtengsmart.github.io"

# 当绑定自定义域名时，将上面改为：
# baseurl: ""
# url: "https://longtengsmart.com"

# 去掉 .html 后缀
permalink: pretty

# 启用相对链接
relative_links:
  enabled: true
  collections: true

# 允许没有front matter的文件
optional_front_matter:
  remove_originals: true 