plugins:
  - jekyll-optional-front-matter

# 设置基础URL - 现在直接部署到根域名，无需子路径
baseurl: ""
url: "https://longtengsmart.github.io"

# 如果将来绑定自定义域名：
# baseurl: ""
# url: "https://longtengsmart.com"

# 去掉 .html 后缀
permalink: pretty

# 启用相对链接
relative_links:
  enabled: true
  collections: true

# 允许没有front matter的文件
optional_front_matter:
  remove_originals: true 